<?xml version="1.0" encoding="utf-8"?>
<geo:GeoInformatieObjectVaststelling xmlns:basisgeo="http://www.geostandaarden.nl/basisgeometrie/1.0"
                                     xmlns:gio="https://standaarden.overheid.nl/stop/imop/gio/"
                                     xmlns:gml="http://www.opengis.net/gml/3.2"
                                     xmlns:geo="https://standaarden.overheid.nl/stop/imop/geo/"
                                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                     xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/geo/ https://standaarden.overheid.nl/stop/1.1.0/imop-geo.xsd"
                                     schemaversie="1.1.0">
   <geo:context>
      <gio:GeografischeContext>
         <gio:achtergrondVerwijzing>TOP10NL</gio:achtergrondVerwijzing>
         <gio:achtergrondActualiteit>2019-01-01</gio:achtergrondActualiteit>
      </gio:GeografischeContext>
   </geo:context>
   <geo:vastgesteldeVersie>
      <geo:GeoInformatieObjectVersie>
         <geo:FRBRWork>/join/id/regdata/gm0479/2021/maximum_goothoogte_6_m</geo:FRBRWork>
         <geo:FRBRExpression>/join/id/regdata/gm0479/2021/maximum_goothoogte_6_m/nld@2021-07-06;1</geo:FRBRExpression>
         <geo:eenheidlabel>meter</geo:eenheidlabel>
         <geo:eenheidID>http://standaarden.omgevingswet.overheid.nl/eenheid/id/concept/Meter</geo:eenheidID>
         <geo:normlabel>maximum goothoogte 6 m</geo:normlabel>
         <geo:normID>http://standaarden.omgevingswet.overheid.nl/typenorm/id/concept/MaximumBouwhoogte</geo:normID>
         <geo:locaties>
            <geo:Locatie>
               <geo:naam>maximum goothoogte 6 m</geo:naam>
               <geo:geometrie>
                  <basisgeo:Geometrie gml:id="id-3df89ab3-53d1-4ea8-b4c3-02286b8b1d87-xx">
                     <basisgeo:id>3df89ab3-53d1-4ea8-b4c3-02286b8b1d87</basisgeo:id>
                     <basisgeo:geometrie>
                        <gml:MultiSurface gml:id="id-3df89ab3-53d1-4ea8-b4c3-02286b8b1d87-0"
                                          srsName="urn:ogc:def:crs:EPSG::28992">
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113490 503004 113489 503009 113477 503008 113477 503002 113490 503004</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113492 502987 113491 502993 113479 502992 113479 502986 113492 502987</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113493 502971 113493 502976 113480 502976 113481 502970 113493 502971</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113494 502954 113494 502960 113491 502960 113481 502959 113481 502954 113494 502954</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113494 502924 113494 502929 113482 502930 113482 502924 113494 502924</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113494 502907 113494 502913 113481 502913 113481 502908 113494 502907</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113493 502891 113493 502896 113480 502897 113480 502891 113493 502891</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113486 503030 113474 503028 113473 503034 113476 503034 113485 503036 113486 503030</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113458 502992 113450 502992 113450 502998 113459 502998 113461 502998 113461 502992 113458 502992</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113458 502983 113450 502983 113450 502989 113458 502989 113461 502989 113461 502983 113458 502983</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113458 502980 113449 502980 113449 502974 113457 502974 113460 502974 113460 502980 113458 502980</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113457 502971 113449 502971 113449 502965 113457 502965 113460 502965 113460 502971 113457 502971</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113460 502962 113457 502962 113449 502962 113449 502956 113457 502956 113460 502956 113460 502962</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113457 502953 113449 502953 113449 502947 113457 502947 113460 502947 113460 502953 113457 502953</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113457 502924 113449 502924 113449 502930 113457 502930 113460 502930 113460 502924 113457 502924</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113457 502921 113449 502921 113449 502915 113458 502915 113460 502915 113460 502921 113457 502921</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113460 502912 113458 502912 113449 502912 113449 502906 113458 502906 113460 502906 113460 502912</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113458 502903 113450 502903 113450 502897 113459 502897 113461 502897 113461 502903 113458 502903</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113461 502888 113460 502888 113450 502888 113450 502894 113459 502894 113461 502894 113461 502888</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113460 502879 113451 502879 113451 502885 113460 502885 113462 502885 113462 502879 113460 502879</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113461 502870 113452 502870 113452 502876 113460 502876 113463 502876 113463 502870 113461 502870</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                           <gml:surfaceMember>
                              <gml:Surface>
                                 <gml:patches>
                                    <gml:PolygonPatch>
                                       <gml:exterior>
                                          <gml:LinearRing>
                                             <gml:posList>113457 502861 113453 502861 113453 502866 113453 502867 113461 502867 113464 502867 113464 502861 113457 502861</gml:posList>
                                          </gml:LinearRing>
                                       </gml:exterior>
                                    </gml:PolygonPatch>
                                 </gml:patches>
                              </gml:Surface>
                           </gml:surfaceMember>
                        </gml:MultiSurface>
                     </basisgeo:geometrie>
                  </basisgeo:Geometrie>
               </geo:geometrie>
               <geo:kwantitatieveNormwaarde>6</geo:kwantitatieveNormwaarde>
            </geo:Locatie>
         </geo:locaties>
      </geo:GeoInformatieObjectVersie>
   </geo:vastgesteldeVersie>
</geo:GeoInformatieObjectVaststelling>
